// Bypassing the '@' alias to force TypeScript to find the file
import { getEnv } from "../../../lib/kv";
import { buildPageMetadata } from "../../../lib/page-meta";

// Define the exact structure of the Digest data to fix all the 'any' type errors
interface DigestSection {
  heading: string;
  items: string[];
}

interface WeeklyDigest {
  weekId: string;
  titleEn: string;
  titleZh: string;
  summaryEn: string;
  summaryZh: string;
  sections: DigestSection[];
  generatedAt: string;
}

export const revalidate = 3600; // Cache page updates hourly

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const isZh = locale === "zh";
  return buildPageMetadata({
    path: "/digest",
    locale,
    title: isZh ? "社区摘要 · Codewhale" : "Community Digest · Codewhale",
    description: isZh
      ? "Codewhale 每周社区更新存档：由维护者审核的摘要。"
      : "Archive of weekly Codewhale community updates — maintainer-approved summaries.",
  });
}

export default async function DigestArchivePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const isZh = locale === "zh";

  // 1. Get the correct project environment bindings
  const env = await getEnv();
  const kv = env.CURATED_KV;

  // Fallback array if no data is found or if KV isn't active in dev
  let digests: WeeklyDigest[] = [];

  if (kv) {
    try {
      // Fetch all weekly digest keys generated by the agent tasks
      const { keys } = await kv.list({ prefix: "digest:weekly-" });

      if (keys && keys.length > 0) {
        const digestsRaw = await Promise.all(
          keys.map(async (k: { name: string }) => {
            const data = await kv.get(k.name);
            return data;
          })
        );

        // Parse each entry independently so a single malformed record can't
        // blank the entire archive — skip only the bad ones.
        digests = digestsRaw
          .filter((item: string | null): item is string => Boolean(item))
          .flatMap((item: string) => {
            try {
              return [JSON.parse(item) as WeeklyDigest];
            } catch (e) {
              console.error("Skipping malformed digest entry:", e);
              return [];
            }
          })
          .sort((a: WeeklyDigest, b: WeeklyDigest) =>
            new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime()
          );
      }
    } catch (e) {
      console.error("Error reading from KV:", e);
    }
  }

  // Handle empty state gracefully
  if (digests.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-center max-w-xl mx-auto px-4">
        <h1 className="text-3xl font-bold mb-4 tracking-tight">
          {isZh ? "社区摘要" : "Community Digest"}
        </h1>
        <p className="text-gray-500 dark:text-gray-400">
          {isZh
            ? "本周社区动态整理中，请稍后再来！"
            : "We are gathering this week's community updates. Check back soon!"}
        </p>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <h1 className="text-4xl font-extrabold mb-2 tracking-tight">
        {isZh ? "每周社区更新" : "Weekly Community Updates"}
      </h1>
      <p className="text-gray-500 dark:text-gray-400 mb-8">
        {isZh ? "由 Codewhale 维护者审核的摘要" : "Maintainer-approved summaries from Codewhale"}
      </p>

      <div className="space-y-12">
        {digests.map((digest: WeeklyDigest) => (
          <article key={digest.weekId} className="border border-gray-200 dark:border-gray-800 rounded-xl p-6 shadow-sm bg-white dark:bg-black">
            <header className="mb-6 border-b border-gray-100 dark:border-gray-900 pb-4">
              <span className="text-xs bg-blue-50 text-blue-600 dark:bg-blue-950/50 dark:text-blue-400 px-2.5 py-1 rounded-md font-mono uppercase">
                {digest.weekId}
              </span>
              <h2 className="text-2xl font-bold mt-3 text-gray-900 dark:text-gray-50">{digest.titleEn}</h2>
              <h3 className="text-xl text-gray-500 dark:text-gray-400 mt-1 font-medium">{digest.titleZh}</h3>
            </header>

            <div className="mb-6 space-y-4">
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">{digest.summaryEn}</p>
              <p className="text-gray-500 dark:text-gray-400 leading-relaxed italic">{digest.summaryZh}</p>
            </div>

            <div className="space-y-6">
              {digest.sections.map((section: DigestSection, idx: number) => (
                <section key={idx} className="border-l-2 border-gray-200 dark:border-gray-800 pl-4">
                  <h4 className="font-bold text-lg mb-2 text-gray-900 dark:text-gray-100">{section.heading}</h4>
                  <ul className="list-disc list-inside space-y-1 text-gray-600 dark:text-gray-400 font-mono text-sm">
                    {section.items.map((item: string, itemIdx: number) => (
                      <li key={itemIdx}>{item}</li>
                    ))}
                  </ul>
                </section>
              ))}
            </div>
          </article>
        ))}
      </div>
    </div>
  );
}
